### ISSUE TITLE
Faire l'interface graphique du raytracer

### ISSUE THREAD

**Issue by bahmez** [Saverio976/Raytracer#174]
Déplacement avec la souris : Lorsqu'on swap sur l'écran on peut se déplacer

Zoom de-zoom avec le scroll (augmentation/diminution du y)

augmentation/diminution du focal avec le crtl + scroll

**Comment by Saverio976** [comment]
- binding touche shift et espace (à la place de rf)
- cancel quit
- switch parameter avec le cli
- modifier sur la csfml le nb de cluster quand en mouvement
- exception custom (avec log)
- bar de progression de render
